include ~/.config/kitty/kitty.conf
allow_remote_control socket-only
listen_on unix:/tmp/kitbar
background_opacity 0.6
allow_multiple_windows yes
clear_all_shortcuts yes
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard